spring:
  application:
    name: service-acl

  datasource:
    url: jdbc:mysql://localhost:3306/guli_acl?serverTimezone=GMT%2B8
    username: root
    password: 721000
    type: com.zaxxer.hikari.HikariDataSource

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8086

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0